"""
Pydantic data models for the trading system.
All models are JSON serializable and include validation.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Literal, Optional
from decimal import Decimal
from datetime import datetime, timezone
from enum import Enum


class Instrument(str, Enum):
    """Supported Oanda instruments"""
    EUR_USD = "EUR_USD"
    GBP_USD = "GBP_USD"
    USD_JPY = "USD_JPY"
    AUD_USD = "AUD_USD"
    USD_CAD = "USD_CAD"


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Side(str, Enum):
    """Trade side"""
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    """Order type"""
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"


class OrderStatus(str, Enum):
    """Order status"""
    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIAL_FILL = "partial_fill"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    FAILED = "failed"


class MarketTick(BaseModel):
    """Normalized market data tick from Oanda"""
    instrument: Instrument
    timestamp: datetime = Field(default_factory=utcnow)
    bid: Decimal = Field(ge=0)
    ask: Decimal = Field(ge=0)
    bid_volume: Optional[int] = None
    ask_volume: Optional[int] = None
    spread: Decimal = Field(ge=0)
    source: str = "oanda"
    data_version: str = "1.0.0"

    @field_validator('spread', mode='before')
    @classmethod
    def calculate_spread(cls, v, info):
        """Calculate spread if not provided"""
        if v is None and 'ask' in info.data and 'bid' in info.data:
            return info.data['ask'] - info.data['bid']
        return v

    @field_validator('ask')
    @classmethod
    def validate_bid_ask(cls, v, info):
        """Ensure ask >= bid"""
        if 'bid' in info.data and v < info.data['bid']:
            raise ValueError(f"Ask price {v} must be >= bid price {info.data['bid']}")
        return v


class TradeSignal(BaseModel):
    """Trade signal generated by Strategy Agent"""
    signal_id: str = Field(description="Unique signal identifier")
    instrument: Instrument
    side: Side
    quantity: int = Field(gt=0, description="Units to trade")
    confidence: float = Field(ge=0.0, le=1.0)
    rationale: str = Field(min_length=10)
    strategy_name: str
    strategy_version: str
    entry_price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    timestamp: datetime = Field(default_factory=utcnow)
    metadata: dict = Field(default_factory=dict)


class RiskCheckResult(BaseModel):
    """Result of risk pre-trade check"""
    signal_id: str
    approved: bool
    reasons: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    risk_metrics: dict = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=utcnow)


class Order(BaseModel):
    """Order to be executed"""
    order_id: str
    signal_id: str
    instrument: Instrument
    side: Side
    quantity: int
    order_type: OrderType
    price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime = Field(default_factory=utcnow)
    updated_at: datetime = Field(default_factory=utcnow)
    oanda_order_id: Optional[str] = None


class Execution(BaseModel):
    """Execution/fill report"""
    execution_id: str
    order_id: str
    instrument: Instrument
    side: Side
    filled_quantity: int
    fill_price: Decimal
    commission: Decimal = Decimal("0")
    timestamp: datetime = Field(default_factory=utcnow)
    oanda_transaction_id: str


class Position(BaseModel):
    """Current position"""
    position_id: str = Field(description="Unique position identifier")
    instrument: Instrument
    side: Side
    quantity: int = Field(gt=0, description="Position size in units")
    entry_price: Decimal = Field(description="Average entry price")
    current_price: Decimal = Field(description="Current market price")
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    unrealized_pnl: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")
    opened_at: datetime = Field(default_factory=utcnow)
    last_updated: datetime = Field(default_factory=utcnow)

    # Alias for backward compatibility
    @property
    def average_price(self) -> Decimal:
        """Alias for entry_price"""
        return self.entry_price


class HealthMetric(BaseModel):
    """System health metric"""
    component: str
    metric_name: str
    value: float
    timestamp: datetime = Field(default_factory=utcnow)
    status: Literal["healthy", "warning", "critical"]
    metadata: dict = Field(default_factory=dict)
