#!/bin/bash
# Script to run all agents in separate terminals

echo "Starting Oanda Trading System..."
echo ""
echo "Run each command in a separate terminal:"
echo ""
echo "Terminal 1 - Market Data Agent:"
echo "  cd /home/joe/Desktop/Algo_trading/oanda-trading-system"
echo "  python -m agents.market_data.agent"
echo ""
echo "Terminal 2 - Monitoring Agent:"
echo "  cd /home/joe/Desktop/Algo_trading/oanda-trading-system"
echo "  python -m agents.monitoring.agent"
echo ""
echo "Terminal 3 - Strategy Agent:"
echo "  cd /home/joe/Desktop/Algo_trading/oanda-trading-system"
echo "  python -m agents.strategy.agent"
echo ""
echo "Terminal 4 - Risk Agent:"
echo "  cd /home/joe/Desktop/Algo_trading/oanda-trading-system"
echo "  python -m agents.risk.agent"
echo ""
echo "Terminal 5 - Execution Agent:"
echo "  cd /home/joe/Desktop/Algo_trading/oanda-trading-system"
echo "  python -m agents.execution.agent"
echo ""
echo "Press Ctrl+C in each terminal to stop"
